### ISSUE TITLE
about requirements

### ISSUE THREAD

**Issue by Shanewbx** [Elenairene/torch-hmsmnet#1]
There is no 'requirements.txt' file in the project.
So,whatWhat environment configuration is needed for this project?

**Comment by Elenairene** [comment]
> There is no 'requirements.txt' file in the project. So,whatWhat environment configuration is needed for this project?

I'm sorry for being busy lately. As I remember the required configurations are python==3.7  torch==1.7.0 and pillow. Other versions may work as well as long as the above package equipped.
 I will complete this repo, upload the requirements and necessary checkpoints before May 1st, 0:00 in the GMT+8 time zone.

**Comment by Shanewbx** [comment]
> > There is no 'requirements.txt' file in the project. So,whatWhat environment configuration is needed for this project?
> 
> I'm sorry for being busy lately. As I remember the required configurations are python==3.7 torch==1.7.0 and pillow. Other versions may work as well as long as the above package equipped. I will complete this repo, upload the requirements and necessary checkpoints before May 1st, 0:00 in the GMT+8 time zone.

Thank you so much❀
