### ISSUE TITLE
WHUStereo数据集测试

### ISSUE THREAD

**Issue by CloseSensor** [Elenairene/torch-hmsmnet#4]
作者您好，为什么用提供的pytorch版本的HMSMNet达不到  [https://ieeexplore.ieee.org/abstract/document/10044710](url) WHUStereo论文中的精度呢？
我根据原论文的训练策略得到的结果以及您在主页上展示的结果的D1都与论文中的相差了15%左右

**Comment by Elenairene** [comment]
> 作者您好，为什么用提供的pytorch版本的HMSMNet达不到 [https://ieeexplore.ieee.org/abstract/document/10044710](url) WHUStereo论文中的精度呢？ 我根据原论文的训练策略得到的结果以及您在主页上展示的结果的D1都与论文中的相差了15%左右

我也不知道orz
如果你复现出来了，请您赐教orzzz

**Comment by chenghao-matrix** [comment]
> > 作者您好，为什么用提供的pytorch版本的HMSMNet达不到 [https://ieeexplore.ieee.org/abstract/document/10044710](url) WHUStereo论文中的精度呢？ 我根据原论文的训练策略得到的结果以及您在主页上展示的结果的D1都与论文中的相差了15%左右
> 
> 我也不知道orz 如果你复现出来了，请您赐教orzzz

复现的作者你好，能进一步沟通一下吗？你最后复现出来了吗？能否加下您的QQ。或者加我的：996936402
